@HOST = http://localhost:3001/admin/menus
@menuId = 62102e61544b40d62ac074cc
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcm1hbCBVc2VyIiwic3ViIjoiNjIxMDJkZGE1ZmFkM2RjYWVlODM1NDYyIiwiaWF0IjoxNjQ1MjI3NDgyLCJleHAiOjE2NDUyNjM0ODJ9.eG7w7EowxvoGFQmOMPt0uG7H_l6jYtMN84AyBFozsQk

### GET all menus
GET {{HOST}}
Authorization: Bearer {{token}}

### GET menu by id
GET {{HOST}}/{{menuId}}
Authorization: Bearer {{token}}

### GET menu by id populated
GET {{HOST}}/{{menuId}}/editor
Authorization: Bearer {{token}}

### POST new menu
POST {{HOST}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Chicken Chicken",
    "isActive": true
}

### Delete menu (optional type=soft) only hard deletes categories and dishes
DELETE {{HOST}}/{{menuId}}?type=hard
Authorization: Bearer {{token}}