services:
       e2e-tests-service:
          container_name: oap-test-e2e
          image: oap-test-e2e
          build: 
            context: ./
            dockerfile: Dockerfile
          ports:
            - "${DOCKER_PORT_OUT}:${DOCKER_PORT_IN}"
          links:
            - mongo
          depends_on:
            - mongo
          command: sh -c "npm run test:e2e"

       mongo:     
          container_name: mongo
          image: mongo:5
          ports:
            - "27017:27017"
          logging:
              driver: "none"
          command: --bind_ip_all
