version: "3.7"
services:
  backend-server:
    command: sh -c "ls && npm run start"
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
      target: full
    ports:
      - "${DOCKER_PORT_OUT}:${DOCKER_PORT_IN}"
    links:
      - oap-mongo:mongo
    depends_on:
      - oap-mongo
    
  oap-mongo:
    image: mongo:5
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    ports:
      - "${DOCKER_DB_PORT_OUT}:${DOCKER_DB_PORT_IN}"
    logging:
      driver: "local"
volumes:
  mongodb: