services:
       backend-server:
           container_name: oap-backend-server
           image: oap-backend
           command: sh -c "npm run start"
           restart: always
           env_file:
            docker.env
           build: 
              context: ./
              dockerfile: Dockerfile
              target: full
           ports:
             - "${DOCKER_PORT_OUT}:${DOCKER_PORT_IN}"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo:5
             volumes:
               - ./data:/data/db
             ports:
               - "27017:27017"