version: "3.7"
services:
  backend:
    container_name: oap-backend
    image: coffeemakingtoaster/oap-backend:latest
    restart: always
    ports:
      - "4001:3000"
    links:
      - mongo
    depends_on:
      - mongo
    
  mongo:
    container_name: oap-backend-db
    image: mongo:5
    restart: always
    volumes:
      - ./home/mongodb:/home/mongodb
      - ./data:/data/db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=OrderAndPay
      - MONGO_INITDB_ROOT_PASSWORD=UedD8WR2U8Amv3t2
      - MONGO_INITDB_DATABASE=wop
    logging:
      driver: "none"