services:
      backend-server-dev:
        container_name: oap-backend-dev
        command: sh -c "npm install && npm run start"
        build:
          context: ./
          dockerfile: Dockerfile
          target: dev
        working_dir: /usr/src/oap-backend-dev
        volumes:
          - ./:/usr/src/oap-backend-dev:cached
        ports:
          - "${DOCKER_PORT_OUT}:${DOCKER_PORT_IN}"
        links:
          - mongo
      mongo:
        container_name: mongo
        image: mongo:5
        volumes:
          - ./data:/data/db
        ports:
          - "27017:27017"