@HOST = http://localhost:3000
@AUTH_TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inh5eiIsInN1YiI6IjYxYTBmZTYzMmYzNDhhOGIwMjg4MTZlOCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjM3OTQxMTU3LCJleHAiOjE2Mzc5NzcxNTd9.W5u23I5O8l-iqZCsvLt4LMHFdsrjLVauzMqnSjh21gE

### Get current User
GET {{HOST}}/user/profile
Authorization: {{AUTH_TOKEN}}

### Get all User (Protected Route for Testing Reasons, access only with admin role)
GET {{HOST}}/user
Authorization: {{AUTH_TOKEN}}

### Patch user by id 
PATCH {{HOST}}/user/6116b5a5c5eae23f344d2d23
Content-Type: application/json

{
    "role": "d",
    "username": "Haha",
    "email": "45@email.com"
}

### Patch user by id 
PATCH {{HOST}}/user/testing/6117eeedb63fd833e0e5145e
Content-Type: application/json

{
    "role": "admin"
}

### Delete User
DELETE {{HOST}}/user/61152d6fb3dac55cbcd081f2

### 
GET {HOST}}/user/verify/98e97d273c8345eac435edeeb15a143c248f529cb07df581730512da1f77b8662c50265967f66f7592ec905213f5ffbab37dbd7aa1c9c13fedde8372fd62106a

### Rerequest verify

GET {{HOST}}/user/getVerify
Authorization: {{AUTH_TOKEN}}

### ResetPassword
GET {{HOST}}/user/password-reset
Content-Type: application/json

{
    "userMail": "xyz@gmail.de"
}

### Reset password (change code)
POST {{HOST}}/user/password-reset/284a2a050082eac63e7e0617daf69d606e8200fce1a0dc6e817902f35ea2394e5f803fc66bf5440e5bd74c8c5bf3fed75099c13dc9eae0d2d835193ce801369e
Content-Type: application/json

{
    "password": "this password was updated"
}

###
POST {{HOST}}/user/submitReset
Content-Type: application/json

{
    "password": "funky",
    "code":"fresh"
}
