@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcm1hbCBVc2VyIiwic3ViIjoiNjIxMDI2ZGVkZGZhZGQwMTc2Y2U1MjI2IiwiaWF0IjoxNjQ1MjI1NzE2LCJleHAiOjE2NDUyNjE3MTZ9.1j9k5uqCYc-W0XUATbxy8LjXK6Y27Fy9JbPz4j1_5lQ
@user = 621026deddfadd0176ce5226
@adress = http://localhost:3001/admin/users

### GET current User
GET {{adress}}/profile
Authorization: Bearer {{token}}

### GET all User
GET {{adress}}
Authorization: Bearer {{token}}

### PATCH user by id 
PATCH {{adress}}/{{user}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "role": "d",
    "username": "Haha",
    "email": "45@email.com"
}

### DELETE User
DELETE {{adress}}/{{user}}
Authorization: Bearer {{token}}
