@host = http://localhost:3001
@allergenId = 620bbd085ea9f3527497f13c
### POST one allergen
POST {{host}}/admin/allergens
Content-Type: application/json

{
    "title": "Steve",
    "icon": "dave"
}

### GET all allergens
GET {{host}}/admin/allergens

### GET one allergen
GET {{host}}/admin/allergens/{{allergenId}}

### GET refs in dishes of allergen
GET {{host}}/admin/allergens/{{allergenId}}/refs

### PATCH one allergen
PATCH {{host}}/admin/allergens/{{allergenId}}
Content-Type: application/json

{
    "title": "Muck",
    "icon": "dave"
}

### Delete Allergen and recursively remove from Dishes
DELETE {{host}}/admin/allergens/{{allergenId}}