@HOST =  http://localhost:3000/tables
@tableId = 61aa21072ca5b1d6969cce88
### Create table
POST {{HOST}}
Content-Type: application/json

{
    "tableNumber": "4",
    "capacity": 1,
    "createdBy": "12"
}

### Get all tables
GET {{HOST}}

### Get table by id
GET {{HOST}}/{{tableId}}

### Patch table information
PATCH  {{HOST}}/{{tableId}}
Content-Type: application/json

{
    "tableNumber": "5",
    "capacity": 1
}

### Delete table by id
DELETE {{HOST}}/{{tableId}}