### Create table
POST http://localhost:3000/tables
Content-Type: application/json

{
    "tableNumber": 1,
    "capacity": 4
}

### Get all tables
GET http://localhost:3000/tables

### Get table by id
GET http://localhost:3000/tables/6183bf0bac92df1094bd7caf

### Patch table information
PATCH http://localhost:3000/tables/6183bf0bac92df1094bd7caf
Content-Type: application/json

{
    "tableNumber": 2,
    "capacity": 3
}

### Delete table by id
DELETE http://localhost:3000/table/6182c71c97e30938282b69a9