@HOST =  http://localhost:3000/tables
@tableId = 61a752a5dac31c57eeea1de4
### Create table
POST {{HOST}}
Content-Type: application/json

{
    "tableNumber": "3",
    "capacity": 4,
    "createdBy": "12"
}

### Get all tables
GET {{HOST}}tables

### Get table by id
GET {{HOST}}/{{tableId}}

### Patch table information
PATCH {{HOST}}/{{tableId}}
Content-Type: application/json

{
    "tableNumber": "5",
    "capacity": 142
}

### Delete table by id
DELETE {{HOST}}/{{tableId}}