version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo:5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    logging: 
      driver: "none"

  backend:
    build: .
    command: sh -c "npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
