version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo:5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  backend:
    build:
      target: dev
    depends_on:
      - mongo
