@HOST=http://localhost:3001/client

### Create new order
POST {{HOST}}/order
Content-Type: application/json

{
    "tableNumber": "1A",
    "items": [],
    "price": 0
}

### Get the current menu 
GET {{HOST}}/menu