@adress = http://localhost:3001/admin/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcm1hbCBVc2VyIiwic3ViIjoiNjIwZjhiMWFhMWUwM2Y1MTFlOTU3NjQwIiwiaWF0IjoxNjQ1MTkwNjU3LCJleHAiOjE2NDUyMjY2NTd9.tmXfwvmRnS_hbyoOY28bScNJ7hZD1rjdD0z0w_Y_5r8
### Register User
POST {{adress}}/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "Normal User",
    "email": "normaluser@gmail.de",
    "password": "adsdfhjngegra"
}

### Login User
POST {{adress}}/login
Content-Type: application/json

{
    "email": "normaluser@gmail.de",
    "password": "adsdfhjngegra"
}
