@adress = http://localhost:3001/admin/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcm1hbCBVc2VyIiwic3ViIjoiNjIxMGY2ODNlMWQ5ZDYyNjdmMTA0OTg2IiwiaWF0IjoxNjQ1Mjc4ODUxLCJleHAiOjE2NDUzMTQ4NTF9.bZGH9WrQosawPVVlWEXFmCYygsHQbs46IjBiT1HpwNc

### Register User
POST {{adress}}/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "New User",
    "email": "newuser@gmail.de",
    "password": "newuserpw"
}

### Login User
POST {{adress}}/login
Content-Type: application/json

{
    "email": "kobibenotet@gmail.de",
    "password": "adsdfhjngegra"
}
