name: Validate Docker Image
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup env
        run: 'echo "$ENV_VALUES" > .env'
        shell: bash
        env:
          ENV_VALUES: ${{secrets.PIPELINE_DOCKER_ENV}}
        
        
      - name: Build the stack
        run: docker-compose up -d
        
      - name: Test
        run: curl -s --retry 10 --retry-connrefused http://localhost:3000/
