name: Test and Build

on:
    push:
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: create env
              run: 'echo "$ENV_VALUES" > .env'
              shell: bash
              env:
                  ENV_VALUES: ${{secrets.PIPELINE_DOCKER_ENV}}

            - name: install dependencies
              run: npm i

            - name: e2e-tests
              run: npm run test:e2e

            - name: unit tests
              run: npm run test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                token: ${{ secrets.CODECOV_SECRET }}
